### ISSUE TITLE
Errors found when running tests

### ISSUE THREAD

**Issue by kwryankrattiger** [IBAMR/IBAMR#1306]
I was running the tests and I found a few cases that crashed/took longer than 10 minutes.

Attached:
[LastTestsFailed_20210721-1648.log](https://github.com/IBAMR/IBAMR/files/6857705/LastTestsFailed_20210721-1648.log)
[LastTest_20210721-1648.log](https://github.com/IBAMR/IBAMR/files/6857706/LastTest_20210721-1648.log)

**Comment by drwells** [comment]
How did you run the tests? If it was on GitHub's CI then I am not too surprised - we are not yet configuring MPI in such a way that we can actually use more than two cores. If you look at the list of failures then only one test (in 3D) failed with two cores. We should add that particular test to the list of tests to avoid on CI but otherwise I believe this is covered by the exclusion regex in that case.

The other test that failed was run with `expect_error=true`, i.e., it is supposed to fail.

**Comment by drwells** [comment]
In particular, I see a lot of bus errors - that's not IBAMR, that's some problem with how the dependencies were compiled. Did you use the older dependency images that still used `march=native`?

**Comment by drwells** [comment]
Fundamentally, this issue referred to tests failing when run with ctest in the CI. This has long since been fixed.
