### ISSUE TITLE
executeIntegrateHierarchyCallbackFcns behavior in the outermost derived class

### ISSUE THREAD

**Issue by Raamkrishnan** [IBAMR/IBAMR#1636]
Hi @boyceg ,

We have ```PhaseChangeHierarchyIntergrator (PCHI)``` derived from ```AdvDiffSemiImplicitHierarchyIntegrator (ADSIHI)``` class. The derived class PCHI calls the ```ADSIHI::integrateHierarchy()``` in its ```integrateHierarchy()```. The derived class PCHI also calls the ```executeIntegrateHierarchyCallbackFcns()``` at the end of ```integrateHierarchy()```.  This is needed if we want to modify or reset the solution before the next cycle. The problem is the base class ADSIHI also calls the ```executeIntegrateHierarchyCallbackFcns``` function in the ```integrateHierarchy``` function. Eventually, ```executeIntegrateHierarchyCallbackFcns``` is executed twice: One in the ADSIHI and the other in the PCHI. Do you have any suggestions for this?

**Comment by drwells** [comment]
I didn't see this back in August - yes, the callback sequence doesn't make sense in some places (it should be outermost to innermost). Lets make sure this is fixed for the 0.14 release.

**Comment by drwells** [comment]
@abarret Can you handle this one?

**Comment by abarret** [comment]
@Raamkrishnan can you point to the lines that are a problem? Looking at #1626, `PhaseChangeHierarchyIntegrator` does not implement `integrateHierarchy()`. I would like to see what you are trying to do that is different than what `AdvDiffSemiImplicitHierarchyIntegrator::integrateHierarchy()` does. Generally, I think the problem is that function was never intended to be overwritten. One option is to introduce additional virtual function calls into `AdvDiffSemiImplicitHierarchyIntegrator::integrateHierarchy()` and continue to let `AdvDiffSemiImplicitHierarchyIntegrator` call the post integration callback functions.

**Comment by Raamkrishnan** [comment]
This is where the problem occurs:

https://github.com/IBAMR/IBAMR/blob/fe14a72f7e899d756f7e2882f916095d6cf849b1/examples/phase_change/ex7/example.cpp#L394C34-L394C45

Instead of ```time_integrator``` if I use ```adv_diff_integrator``` pointer, the callback is executed multiple times:

1. EnthalpyHierarchyIntegrator:: executePostprocessIntegrateHierarchyCallbackFcns()
2. PhaseChangeHierarchyIntegrator:: executePostprocessIntegrateHierarchyCallbackFcns()
3. AdvDiffSemiImplicitHierarchyIntegrator:: executePostprocessIntegrateHierarchyCallbackFcns()

It should be executed only once in the outermost derived class.

**Comment by boyceg** [comment]
If you call the base class's implementation of `postProcessIntegrateHierarchy`, then the user-provided post-processing routines will always be called from there. (Same story with pre-processing routines in `preProcessIntegrateHierarchy`.)

One solution is to remove the calls to the user-provided routines from the derived classes' implementations and just use the base class to do this.

The other solution is not to call the base class's implementations of these routines, and to do everything in the derived class.

I don't think it is necessary to add additional virtual functions etc. in this case.

**Comment by abarret** [comment]
The problem here is that `executeIntegrateHierarchyCallbackFcns` is expected to be called at the end of `integrateHierarchy()`. If you want to use the base class's implementation of `integrateHierarchy()` but modify the result in the derived class, then `executeIntegrateHierarchyCallbackFcns` will not be performed last. One option is what @boyceg suggested. You can just copy and paste the bits and pieces of the base class's implementation and never call the base class's code. This is not ideal as we're duplicating code. It can also lead to confusion as some derived classes will call the base implementation but others do not.

My suggestion is to separate `integrateHierarchy()`  into two routines: a function that performs advection + diffusion and a function that calls the previous function along with `executeIntegrateHierarchyCallbackFcns`. The code would look something like
```c++
class AdvDiffSemiImplicitHierarchyIntegrator : public AdvDiffHierarchyIntegrator
{
void integrateHierarchy() override
{
    AdvDiffHierarchyIntegrator::integrateHierarchy();
    doIntegrateHierarchy();
    executeIntegrateHierarchyCallbackFcns();
}
virtual void doIntegrateHierarchy() {
   // Perform advection + diffusion integration
}
}
```
In this way, you can still call the base class's implementation of `doIntegrateHierarchy()` without having to execute the callback functions. We could even push this method of executing the callbacks all the way to back to the base class `HierarchyIntegrator` and perhaps remove `integrateHierarchy()` from being `virtual`.
