### ISSUE TITLE
Hierarchy Integrators do not call setDataOnPatchHierarchy during initial time step

### ISSUE THREAD

**Issue by abarret** [IBAMR/IBAMR#747]
The hierarchy integrators do not call `setDataOnPatchHierarchy` for any registered forcing terms. The INS integrators do call `setDataOnPatchLevel`. The IB integrators do not call any INS forcing function. This is not surprising since the hierarchy is created level by level.

This is a problem for cases where the forcing function registers and initializes draw variables. In particular, we have to move the first `allocatePatchData` call to inside `setDataOnPatchLevel`, see for example the class `CFINSForcing`. This fix does not work for simulations with IB integrators, and draw data can not be initialized.

**Comment by boyceg** [comment]
I think that some or all of this initialization code pre-exists `HierarchyIntegrator::initializeCompositeHierarchyData()`.

**Comment by boyceg** [comment]
One alternative would be to call `setDataOnPatchHierarchy()` repeatedly in `HierarchyIntegrator::initializeLevelData()` when constructing the initial patch hierarchy, always using the full range of levels that has been constructed.

**Comment by boyceg** [comment]
See #750.

**Comment by boyceg** [comment]
The only alternative to #750 that I can think of would be to zero-initialize everything in the initial patch hierarchy construction and then to really initialize the variables in `HierarchyIntegrator::initializeCompositeHierarchyData()` using `CartGridFunction::setDataOnPatchHierarchy()`.

The problem is that this will make it impossible to do initial gradient detection in building the patch hierarchy --- does not seem ideal.

**Comment by amneetb** [comment]
> The only alternative to #750 that I can think of would be to zero-initialize everything in the initial patch hierarchy construction and then to really initialize the variables in `HierarchyIntegrator::initializeCompositeHierarchyData()` using `CartGridFunction::setDataOnPatchHierarchy()`.
> 
> The problem is that this will make it impossible to do initial gradient detection in building the patch hierarchy --- does not seem ideal.

Yeah, this will not tag cells in the beginning. 


@abarret Won’t initializing things in initializeCompositeGridHerarchyData work for you?

**Comment by abarret** [comment]
The issue isn't so much that `setDataOnPatchLevel` is called. It's that things are inconsistent among different integrators. The INS integrators call `setDataOnPatchLevel` for a registered forcing term. The IB integrator _does not_ call `setDataOnPatchLevel` for forcing functions registered with the INS integrator.

**Comment by abarret** [comment]
It seems like only the `IBEulerianForceFunction` is being called on level creation, not the entire `CartGridFunctionSet`.

**Comment by amneetb** [comment]
The IB integrator _does not_ call `setDataOnPatchLevel` for forcing functions registered with the INS integrator.

I had to suffer for three days due to this issue. I had registered gravity forcing with INS integrator rather than IB integrator. The pressure was not coming out to be right as a result of this as the gravity forcing was not getting called.

**Comment by abarret** [comment]
This is what I'm coming up with now. I have to register the complex fluid forcing with the IB Integrator instead of the INS integrator to ensure that the IB forcing works correctly. This does not make sense to me.

**Comment by abarret** [comment]
I think I found it. `INSHierarchyIntegrator` does not register multiple body forcing functions correctly. I've got a fix coming.

**Comment by abarret** [comment]
This was fixed by #751. `HierarchyIntegrator`s still do not call `setDataOnPatchHierarchy` on level creation, but this is expected behavior since the patch hierarchy is created level by level.
