### ISSUE TITLE
Put all configuration info in a single header

### ISSUE THREAD

**Issue by drwells** [IBAMR/IBAMR#802]
There are a few places where we conditionally include different libMesh headers based on which version of libMesh we are using. This means that we need to include `libmesh_config.h` before the version check. The best way to do this would be to write a header that contains the configuration headers of all dependencies and put it at the top of each header and source file so that version information is always available.

**Comment by boyceg** [comment]
This could also make it easier to switch build systems. Can we do this ASAP after tagging 0.6?

In the past, I made a concerted effort to avoid including these generated config files in IBAMR header files. What are "best practices" for this kind of thing?

**Comment by knepley** [comment]
We create these files:

  makefile configure header arch-master-debug/lib/petsc/conf/petscvariables
  makefile configure header arch-master-debug/lib/petsc/conf/petscrules
  configure header arch-master-debug/include/petscconf.h
  C specific configure header arch-master-debug/include/petscfix.h
  configure pkg header arch-master-debug/include/petscpkg_version.h

petscconf.h is included by both C and Fortran headers, but petscfix.h only by C headers. The version header includes the versions of packages we installed and macros for checking them because some packages (Hypre) need to check this at compile time.

**Comment by drwells** [comment]
I prefer the approach that PETSc uses in `petscpkg_version.h`; we do approximately the same thing in deal.II but put everything in one header (see https://github.com/dealii/dealii/blob/master/include/deal.II/base/config.h.in).

I would prefer to extract version information in the build system (we have it at that point anyway) and then put it with our own `#define`s in `IBTK_config.h`.

**Comment by drwells** [comment]
We also need to include `libmesh/libmesh_version.h` to get the `LIBMESH_VERSION_LESS_THAN` macro.

**Comment by drwells** [comment]
Lets get to this sooner, rather than later, so that we can start transitioning to a new build system. I will put all configuration information in `ibtk/config.h` and `#include` that in older headers for compatibility. The top level `IBTK_config.h` and `IBAMR_config.h`, `ibtk_macros.h`, `ibamr_macros.h`, `IBTK_CHKERRQ.h`, etc. all need to be absorbed by that header.

**Comment by drwells** [comment]
This is now done for CMake - we just need to backport it (or a shim) to autotools.

**Comment by drwells** [comment]
We are at the point now where `ibtk/config.h` and `ibamr/config.h` satisfy the original goals of this issue.
